# PACKAGES ----------------------------------------------------------------------------------

# Make sure the following are installed. This includes packages that are not on CRAN
# and packages that are not loaded below but instead directly references in the code
# (to avoid having to load packages into memory of which we only use a few functions).
list.of.packages <- 
  c(
    "remotes", 
    "knitr", 
    "tidyverse",        # data wrangling and plotting 
    "magrittr",         # pipes, my friend, we need pipes 
    "magick",           # alternative way to process figures imported through include_graphics
    "assertthat",       # robust argument handling for functions 
    "fuzzyjoin",        # join tables based on relative matching
    "rlang",            # quosures and unquoting
    "ggforce",          # correlation matrices
    "ggnewscale",       # multiple scales
    "ggtext",           # vertical labels via geom_richtext
    "ggh4x",            # constant panel sizes across plots
    "patchwork",        # plotting multiple plots together
    "plotly",           # plotting 3D plots (in SI)
    "ellipse",          # covariance ellipses
    "linguisticsdown",  # IPA symbols
    "Cairo",            # plotting IPA and other special symbols
    # Doesn't interact well with JASA template since it automatically loads a number of 
    # latex packages, including pdflscape, which doesn't interact well with revtex 4.1,
    # which is used by the JASA template.
    # "kableExtra",       # styling tables (HTML formatting)
    "phonR",            # vowel normalization functions
    "phonTools",        # WattFabricius normalization function
    "brms",             # Bayesian mixed-effects multinomials regression
    "cmdstanr", 
    "mgcv",             # GAMMs
    "itsadug",          # GAMM visualization
    "modelr",           # making data grids for model predictions
    "tidybayes",        # working with posterior draws of Bayesian models
    "MVBeliefUpdatr",   # fitting and using Ideal Observers
    "future",           # parallel processing
    "furrr",            # parallel map fur future
    "english"           # convert numbers to text
)
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if (length(new.packages)) {
  if ("remotes" %in% new.packages) install.packages("remotes")
  if ("papaja" %in% new.packages) remotes::install_github("crsh/papaja")
  if ("cmdstanr" %in% new.packages) {
    install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
    cmdstanr::install_cmdstan()
  }
  if ("MVBeliefUpdatr" %in% new.packages) remotes::install_github("hlplab/MVBeliefUpdatr")
  if ("supunsup" %in% new.packages) remotes::install_github("kleinschmidt/phonetic-sup-unsup")
  new.packages <- setdiff(new.packages, c("remotes", "papaja", "cmdstanr", "MVBeliefUpdatr", "supunsup"))

  install.packages(new.packages)
}

for (p in list.of.packages) {
  library(p, character.only = T)
}

# KNITR SETUP -------------------------------------------------------------------------------
# Use fig.process to rename figure files generated by R so that they comply with
# the journal naming policies. Remember to name plot chunks with the format
# "Figure1", "Figure2", etc... You will find the figure files in
# `[...]_files/figure-latex/`.

# The only figure formats allowed for submission are the following: `.pdf`, `.ps`, `.eps`, or `.jpg`.
# Figure files must be named in this fashion:
# `Figure\#.xxx`, where `\#` is the figure number and `xxx` is the file format
# (`Figure1.eps`, `Figure2.jpg`, `Figure3a.ps`, `Figure3b.ps`, etc).

# Function to rename figures for JASA 
# From https://stackoverflow.com/questions/45656258/knitr-automated-figure-numbering-in-the-file-names
make_plot_namer <- function(prefix="Figure", width=2) {
  n <- 0L  # Initialize n to 0
  counter <- 0L  # Initialize a counter variable to 0
  
  function(x) {
    if (counter %% 2 == 0) {
      # Increment n every 2 uses
      n <<- n + 1L
    }
    
    x2 <- file.path(dirname(x), 
                    paste0(prefix, 
                           formatC(n, width=width, flag="0"),
                           ".", 
                           tools::file_ext(x)))
    
    if (file.rename(x, x2)) {
      counter <<- counter + 1L  # Increment the counter after renaming
      x2
    } else {
      x
    }
  }
}

# Function to include external graphics and apply knitr processing so that graphics
# included via include_graphics are subjected to the same automatic processing that 
# figures generated by R are subjected to.
include_graphics <- function(path, caption = NULL, ...) {
  # Create a temporary R plot using magick
  tmp_plot <- function(file) {
       magick::image_read(file) %>%
        magick::image_ggplot() +
        theme_void() # Remove default ggplot elements
  }
  
  # Use knitr's plotting mechanism to capture and process the figure
  # knitr::include_graphics(path, error = FALSE)
  # knitr::opts_chunk$set(fig.show = "asis") 
  # Call the temporary function, which will be processed by knitr
  for (p in path) tmp_plot(p) 
  # knitr::opts_chunk$set(fig.show = NULL) #Reset to default
}

knitr::opts_chunk$set(
  fig.path = "",
  dpi = 150,
  dev = c('cairo_pdf'), # default format of figures
  fig.align = "center",
  fig.process = make_plot_namer(width=1),
  # fig.process = function(x) {
  #   x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
  #   if (file.rename(x, x2)) x2 else x
  # }
  out.width = "\\reprintcolumnwidth",
  echo = FALSE, warning = TRUE, message = TRUE,
  cache = FALSE)

# The JASA LaTeX class depends on the LaTeX package "revtex4-2". If you are
# using a full LaTeX distro, you should make sure "revtex4-2" is installed, and
# install it if not.

# some useful formatting functions for output of knitting
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})

color_block = function(color) {
  function(x, options) sprintf('\\color{%s}\\begin{verbatim}%s\\end{verbatim}\\color{black}',
                               color, x)
}
knitr::knit_hooks$set(error = color_block('red'))
knitr::knit_hooks$set(warning = color_block('orange'))

# Get citation information
papaja::r_refs(
  file = "latex-stuff/r-references.bib",
  append = FALSE,
  type_pref = c("Manual", "Article", "Book"))

# CONSTANTS ----------------------------------------------------------------------------------
set.seed(333421864)

# Make sure to keep aux files etc. after knitting
options(tinytex.clean = FALSE)
options(knitr.table.format = "latex")
base.width = 2.5
base.height = 2.5
base_size = 9

# FUCNTIONS ----------------------------------------------------------------------------------
source("constants-functions.R")
myGplot.defaults("paper")
